### ISSUE TITLE
Python-Web-Scraping-Second-Edition/Chapter05/json_one_req.py  not working

### ISSUE THREAD

**Issue by moondra2017** [PacktPublishing/Python-Web-Scraping-Second-Edition#1]
Hi, When I run the script in the title, I'm getting this error:

`simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by ghost** [comment]
The sample site has been updated so the URLs in the example code have to be updated.
change this line
`template_url = 'http://example.webscraping.com/ajax/' + \`
to
`template_url = 'http://example.webscraping.com/places/ajax/' + \`

Also, for those examples you may need need to add a delay to avoid getting temporarily blocked while scraping the example site.
