### ISSUE TITLE
chapter04 : threaded_crawler_with queue  

### ISSUE THREAD

**Issue by alfredaita** [PacktPublishing/Python-Web-Scraping-Second-Edition#4]
multi-threaded process won't start:
posted on the authors site 
here is the link
https://github.com/kjam/wswp/issues/12#issue-410257980
running windows 10-pro
python 3.6.6
GPU 960m

**Comment by d0tN3t** [comment]
I'm getting the same error as @alfredaita 
Doing a little bit of troubleshooting it seems to break around the Class RedisQueue.
