### ISSUE TITLE
Chapter06_StoringData

### ISSUE THREAD

**Issue by Lysander086** [PacktPublishing/Python-Web-Scraping-Second-Edition#5]
The following code produces many errors on Windows10.
1st: AttributeError: 'module' object has no attribute 'AF_UNIX'
2nd: TypeError: getsockaddrarg: AF_INET address must be tuple, not str
and so on...

Why the code samples provided by this book can't function normally for so many occasions?
It's really not friendly to newbies like me.

`
import datetime
import random
import re
from urllib.request import urlopen

import pymysql
from bs4 import BeautifulSoup

conn = pymysql.connect(host='127.0.0.1', unix_socket='/tmp/mysql.sock',
                       user='root', passwd='code123455', db='mysql', charset='utf8')
cur = conn.cursor()
cur.execute('USE scraping')

random.seed(datetime.datetime.now())

def store(title, content):
    cur.execute('INSERT INTO pages (title, content) VALUES ("%s", "%s")', (title, content))
    cur.connection.commit()

def getLinks(articleUrl):
    html = urlopen('http://en.wikipedia.org' + articleUrl)
    bs = BeautifulSoup(html, 'html.parser')
    title = bs.find('h1').get_text()
    content = bs.find('div', {'id': 'mw-content-text'}).find('p').get_text()
    store(title, content)
    return bs.find('div', {'id': 'bodyContent'}).findAll('a', href=re.compile('^(/wiki/)((?!:).)*$'))

links = getLinks('/wiki/Kevin_Bacon')
try:
    while len(links) > 0:
        newArticle = links[random.randint(0, len(links) - 1)].attrs['href']
        print(newArticle)
        links = getLinks(newArticle)
finally:
    cur.close()
    conn.close()

`

**Comment by githubce** [comment]
Please check the version of Python you are using. There has been a lot of updates in Python since the book was published. Please use the appropriate version.
